### ISSUE TITLE
How to use dataset

### ISSUE THREAD

**Issue by nezumitti** [lvsn/deeptracking#14]
hi MathGaron
I have a rudimentary question.
Although I was able to do normal learning, I could not learn with occlusion and background. As a result, tracking was not successful.
Could you tell me how to use occlusion model and background model (SUN 3 D model)?
In other words, I do not know the data to be included in "occluder_path" and "background_path" used in "train.py".

**Comment by MathGaron** [comment]
Hey,
Sure, it is true that other than the code, I do not explain them very well in the documentation : 
- SUN3D : you just need a folder with subfolders containing rgb and depth file :
   - SUN3D -> 
        -subfolder_name ->
            0.png  (rgb image)
            0d.png (depth image)
            [...]

Note that it could be many subfolders similar as the original SUN3D folder structure.

for the occluder_path, you need to use the datagenerator provided and render them. It is basically the equivalent of your train data. (Don't use too large models as they could hide the whole object and make the training too difficult)

Hope it helps!
Mathieu

**Comment by nezumitti** [comment]
Thank you for answering
I succeeded in re - learning including "background" and "occluder".
However, tracking could not be done normally.
I want to reproduce the tracking.
I want to know which data set of background (SUN 3 D) is used.

**Comment by MathGaron** [comment]
Hey,
Great for the background/occluder! I will check if we can host the images I was used (without licenses issues etc.) Else I use SUN3D scenes, I greedily remove the image that looks too similare (we explain it in the paper briefly).

What do you mean by tracking could not be done normally?

Also I refer you to our more recent paper and code : [here](http://vision.gel.ulaval.ca/~jflalonde/projects/6dofObjectTracking/index.html)

It will converge to a much better solution, and you also don't need the real data which makes the setup simpler.

**Comment by nezumitti** [comment]
As a result of learning based on the published dataset, tracking is lost.
 [Just like this](https://github.com/lvsn/6DOF_tracking_evaluation/issues/3)

I want to use "deep tracker" based on my own made model, so the primary goal is to achieve your code exactly.

**Comment by MathGaron** [comment]
Yes this happens when a model don't converge correctly, and many things can trigger such a bug, so I here is my first question:

- Which version of deeptrack are you using? the one with the normal conv layer(TVCG17) or the one based on the Fire module(ECCV18)

if you use the one with the conv, you have to add real training samples in the training, I suggest using the ECCV18 model which simply need the occluders and backgrounds. the implementation is on the github and it achieve much better results.

**Comment by nezumitti** [comment]
I may have misunderstood a bit.
I implemented "TVCG 17".
My question is, in the implementation of "ECCV 18", can I use "deep tracker" on my own model?
I would like to apply this "deep tracker" to various objects.
Sorry to ask a question many times.

**Comment by MathGaron** [comment]
I might have confused with the term "deep tracker". I just use it for the tracking model!

So the network of ECCV18 is quite similar, just look in the code and change your model. There is also a slight change in the way we sample the data when we generate the dataset, you might want to use the new tools also. For best performances, you can still train on a single object, and you will have the best results for this object.
The main advantage is that you won't need to use the real data which can be annoying to generate and merge with the synthetic data.
And finally, ECCV18 can generalize to multiple objects, you simply need to train it with various 3D models (~30 +) ( that you can download a few from [BOP benchmark](http://openaccess.thecvf.com/content_ECCV_2018/html/Tomas_Hodan_PESTO_6D_Object_ECCV_2018_paper.html)

**Comment by nezumitti** [comment]
I understood well!
And we were able to reproduce with ECCV 2018 implementation and the data set you provided.
Thank you very much.
I would like to try it with various objects.
