### ISSUE TITLE
python2.7.6 run capture_data.py errors.

### ISSUE THREAD

**Issue by Myzhencai** [lvsn/deeptracking#5]
HI,I am trying to make the awesome work running in my computer. But when I just installed all the dependences I just find that I get this error ,I think it might be the reason I am using python2 ,any suggestions? Many appreciate your time ,thanks : -).
gaofei@gaofei-HP-Z420-Workstation:~/deeptracking$ python capture_data.py 
Traceback (most recent call last):
  File "capture_data.py", line 1, in <module>
    from deeptracking.detector.detector_aruco import ArucoDetector
ImportError: No module named detector.detector_aruco

**Comment by MathGaron** [comment]
You are right, it was simply a missing __init__.py. Python2 does not recognize a folder without this file as a package, while python3 does.
I pushed the file and it should work now.

I suggest using python3 though, the results are obtained with this version, so I can't guarantee that using python2 will be bugless.

**Comment by Myzhencai** [comment]
@MathGaron thanks
