### ISSUE TITLE
issues about aruco.BoardConfiguration,aruco.BoardDetector

### ISSUE THREAD

**Issue by Myzhencai** [lvsn/deeptracking#6]
@MathGaron  as per the instruction i run the test_sensor.py and i find the error:it says there is no module of  aruco.BoardConfiguration,aruco.BoardDetector and aruco.CameraParameters，do you use some specific aruco right?
BTW, i am using ubuntu14.04,python3.4,aruco3.4,opencv3.4and python-aruco,so it might be the vision of aruco issue?can you share some suggestion?many thanks

**Comment by MathGaron** [comment]
I see that you closed the issue, is everything fine?

Aruco is used for the tools that capture new data (sequence or real data) I realize that I did not document this tool, I will reopen the issue so I remember to do it!

**Comment by Myzhencai** [comment]
@MathGaron I just find that [https://github.com/fehlfarbe/python-aruco/tree/aruco1.3.0](url)have the modules ,and the instruction is use the [https://github.com/jayrambhia/Install-OpenCV/](url)to install the latest opencv and then download the [https://sourceforge.net/projects/aruco/files/OldVersions/](url)aruco1.3.0 then i just follow the instruction in[https://github.com/fehlfarbe/python-aruco/tree/aruco1.3.0](url)to sudo apt-get install swig3.0(for python3),then I run ./swigbuild.sh: it compiles the shared library (_aruco.so) and generates Python wrappers (aruco.py),run sudo python setup.py install --record log to install the library globally.when i rerun the test_sensor.py it do not raise the issue about this .so I think this should be a solution for the issue .
thanks for your reply ,have a nice day.

**Comment by nezumitti** [comment]
Suddenly sorry...
I am building in the same environment.
However, the following error will occur.
```
Traceback (most recent call last):
  File "test_sensor.py", line 96, in <module>
    detector = ArucoDetector(sensor.camera, data["detector_layout_path"])
  File "/home/toshi/deeptracking/deeptracking/detector/detector_aruco.py", line 12, in __init__
    boardconfig = aruco.BoardConfiguration(board_path)
  File "/usr/local/lib/python3.5/dist-packages/aruco.py", line 692, in __init__
    this = _aruco.new_BoardConfiguration(*args)
RuntimeError: <Swig Object of type 'cv::Exception *' at 0x7f3489679c30>
swig/python detected a memory leak of type 'cv::Exception *', no destructor found.

```
Is there anything else you can think about?
