### ISSUE TITLE
asking for the dataset.

### ISSUE THREAD

**Issue by Myzhencai** [lvsn/deeptracking#7]
hi, i just read the paper for the project .we need the dataset for the json file right ?
 "data_augmentation":{
      "rgb_noise": "4",       # std of rgb gaussian noise
      "depth_noise": "20",    # std of depth gaussian noise
      "occluder_path": "/path/to/occluder/dataset",
      "background_path": "/path/to/background/dataset",
      "blur_noise": "7",      # max gaussian blur kernel size
      "h_noise": "0.07",      # max hue noise
      "s_noise": "0.0",       # max saturation noise
      "v_noise": "0.2"        # max intensity noise
},
should i dwonload all the SUN3D database? and can i replace the occluder with any other 3d models?
wish for your reply. have a nice day.
--

**Comment by MathGaron** [comment]
Hi,
Yes you need a dataset, actually, you need 3 different folders:
1 - your object generated from the dataset generator
2 - Backgrounds, you can pick SUN3D as we did, but you need to filter out images that are too similar so you don't bias your training.
3 - Another dataset of an object as the occluder that you also generate from the generator.

**Comment by Myzhencai** [comment]
@MathGaron  oh, thanks . I will try it.
