### ISSUE TITLE
question about traning data

### ISSUE THREAD

**Issue by Myzhencai** [lvsn/deeptracking#8]
@MathGaron @jflalonde ,hi ,according to the paper of the awesome project and the code of the project. I still fell some confused of the training data generation.As far as I can know is  that we use the 3D model texture file (the ply files)and the things in the generate_synthetic_example.json to get the dataset of  input Xpred. And the generate_real_example.json material (include the raw_training images???)are used to get the dataset of input Xobs.But the paper just said we just need  the 3D model file and the P pred,Pobs to generate the training dataset.BTW ,the data is generated as a pair like 0.pny 0n0.pny,so the first time i just think they are Xpred and  Xobs respectively.But i just find the generate_synthetic_data.py do not use the Euler angle notation and do not have the word of previous pose mentioned.so I guess that the two generators just make part of the training data sepetively.am i right?and there is something unnormal is that this is some data generated : they are just away from the paper .
![2018-01-22 15 00 53](https://user-images.githubusercontent.com/21084423/35212244-8154244c-ff94-11e7-8064-f2429cae5fa7.png)
![2018-01-21 20 42 02](https://user-images.githubusercontent.com/21084423/35212274-8f884066-ff94-11e7-99fb-c51918825123.png)

**Comment by MathGaron** [comment]
Hi,

xxxx.png is xobs and xxxxn0.png is xpred.
generate_synthetic_data generates all the images from the 3D model.
generate_real_data generates the same type of image but from real images containing the ground truth. ("Raw training data" on the website) so xobs is synthetic and xpred is from the real image

There is something wrong with your setup, the images should not be black, but contain the object like in the paper. Make sure that everything is fine with the 3D model.

**Comment by Myzhencai** [comment]
I see ,thanks for the specific commentary，I will see more details in the paper and the ppt to get indeed.
thanks for your reply : -). have a nice day.

**Comment by Myzhencai** [comment]
hi @MathGaron ,I have tried to make everything exactly .but it seems there still the output data issue .so does the generator process use the GPU ? If it does I think it might be the issue of that .BTW the ply file is fine cause I just use the some software have look in the windows system,and I use the plyparser you shared with me in the [https://gist.github.com/MathGaron/143a60c7d4440e03b5b11fd00e727250](url),seems there is nothing wrong with that .looking forward your reply.
![2018-01-23 12 54 27](https://user-images.githubusercontent.com/21084423/35258885-563eeab8-003d-11e8-93f7-04023691f9a8.png)

**Comment by MathGaron** [comment]
The generator uses OpenGL, make sure that everything is fine with it. Make sure that there is no warnings/errors on your console. Other than that I don't have enough information to help you further.
